# Project information
site_name: "Madrus's Docs"
site_description: 'A short description of my project'
site_author: 'Madrus'
site_url: 'http://madrus4u.com/mdocs/'
site_favicon: 'images/favicon.ico'

# Repository
#repo_name: 'GitHub'  # will it work with GitLab?
repo_url: 'https://github.com/madrus/mdocs'

# Copyright
copyright: 'Copyright (c) 2016 Madrus'

# Pages structure
pages:
  - Home: index.md
  - MkDocs:
    - Technicalities: mkdocs/technicalities.md
    - Custom Styling: mkdocs/custom_styling.md
  - Umbraco:
    - Technicalities: umbraco/technicalities.md
  - Sandbox:
    - TODOs: sandbox/todo.md
    - Test Document: sandbox/test.md

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  # version: '0.1.0'
  logo: 'images/logo.png'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'madrus'
    twitter: 'madrusnl'

markdown_extensions: 
  - admonition
  - codehilite(css_class=code):
      guess_lang: false
  - nl2br
  - smarty:
      smart_angled_quotes: true
  - toc:
      permalink: '#'

# Google Analytics
google_analytics:
  - 'UA-52692182-5'
  - 'auto'
