# Project information
site_name: "Madrus's Docs"
site_description: 'A short description of my project'
site_author: Madrus
site_url: 'http://madrus4u.com/mdocs/'

# Repository
#repo_name: 'GitHub'  # will it work with GitLab?
repo_url: 'https://github.com/madrus/mdocs'

# Pages structure
pages:
  - Home: index.md
  - MkDocs Engine:
    - Technicalities: engine/technicalities.md
    - Styling: engine/styling.md
  - Aurelia:
    - Some Technical Notes: aurelia/technicalities.md
  - Git:
    - GitFlow: git/gitflow.md
    - Tools: git/tools.md
    - Styling: git/styling.md
    - SSH: git/ssh.md
  - Mac:
    - NGINX: mac/nginx.md
    - SSH on Sierra: mac/ssh.md
    - Tips & Tricks: mac/tips.md
  - .NET Core:
    - New Project: dotnet/new_project.md
    - Notes: dotnet/notes.md
    - Tips: dotnet/tips.md
  - Umbraco:
    - Technicalities: umbraco/technicalities.md
    - FAQ: umbraco/faq.md
  - Vue.js:
    - Vue.js Basics: vuejs/basics.md
  - Webpack:
    - Webpack Basics: webpack/basics.md
  - Playground:
    - TODOs: playground/todo.md
    - Test Document: playground/test.md

# Documentation and theme
theme:
  name: 'material'
  favicon: 'img/favicon.ico'

# Extra assets
#extra_css:
#  - 'css/extra.css'

# Options
extra:
  version: 0.2.0
  logo: 'img/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'madrus'
    twitter: 'madrusnl'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - nl2br
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - fontawesome_markdown
  - smarty:
      smart_angled_quotes: true
  - toc:
      permalink: true


#Copyright
copyright: 'Copyright &copy; 2017 <a href="https://madrus4u.com">Madrus4U</a>'

# Google Analytics
google_analytics:
  - 'UA-52692182-5'
  - 'auto'
