# Project information
site_name: "Madrus's Docs"
site_description: 'A short description of my project'
site_author: Madrus
site_url: 'http://madrus4u.com/mdocs/'

# Repository
repo_name: madrus/mdocs
repo_url: https://github.com/madrus/mdocs
edit_uri: ''

#Copyright
copyright: 'Copyright &copy; 2018 <a href="https://madrus4u.com">Madrus4U</a>'

# Documentation and theme
theme:
  name: 'material'
  language: en
  # feature:
  #   tabs: true
  palette:
    primary: 'blue grey'
    accent: 'lime'
  custom_dir: theme
  favicon: 'img/favicon.ico'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

# Options
extra:
  version: 0.3.0
  logo: 'img/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'madrus'
    twitter: 'madrusnl'

# Google Analytics
google_analytics:
  - 'UA-52692182-5'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - fontawesome_markdown
  - def_list
  - footnotes
  - meta
  - nl2br
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty:
      smart_angled_quotes: true
  - toc:
      permalink: true

# Pages structure
nav:
  - Home: index.md
  - MkDocs Engine:
    - Getting started: engine/technicalities.md
    - Custom Styling: engine/styling.md
    - More on MkDocs Material: engine/install.md
  - Aurelia:
    - Some Technical Notes: aurelia/technicalities.md
  - Git:
    - GitFlow: git/gitflow.md
    - Git Prompt Styling: git/styling.md
    - Set up SSH: git/ssh.md
    - Git Command Line Tools: git/tools.md
  - Mac:
    - NGINX: mac/nginx.md
    - SSH on Sierra: mac/ssh.md
    - Tips & Tricks: mac/tips.md
  - .NET Core:
    - New Project: dotnet/new_project.md
    - Notes: dotnet/notes.md
    - Tips: dotnet/tips.md
  - PowerShell:
    - Debugging PowerShell in VS Code: powershell/vscode.md
  - Umbraco:
    - Technical details: umbraco/technicalities.md
    - Issues and solutions: umbraco/faq.md
  - Vue.js:
    - Vue.js Basics: vuejs/basics.md
  - Webpack:
    - Webpack Basics: webpack/basics.md
  - Playground:
    - TODOs: playground/todo.md
    - Test Document: playground/test.md
