# Project information
site_name: "Madrus's Docs"
site_description: 'A short description of my project'
site_author: Madrus
site_url: 'http://madrus4u.com/mdocs/'

# Repository
repo_name: madrus/mdocs
repo_url: https://github.com/madrus/mdocs
edit_uri: ''

#Copyright
copyright: 'Copyright &copy; 2018 <a href="https://madrus4u.com">Madrus4U</a>'

# Documentation and theme
theme:
  name: 'material'
  language: en
  # feature:
  #   tabs: true
  palette:
    primary: 'blue grey'
    accent: 'lime'
  custom_dir: theme
  favicon: 'img/favicon.ico'
  logo: 'img/logo.png'
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  extra_css:
  - 'assets/stylesheets/extra.css'
  # - 'https://use.fontawesome.com/releases/v5.3.1/css/all.css'
  # - 'https://use.fontawesome.com/releases/v5.3.1/css/v4-shims.css'
  # extra_javascript:
  # - 'https://use.fontawesome.com/releases/v5.3.1/js/all.js'
  # - 'https://use.fontawesome.com/releases/v5.3.1/js/v4-shims.js'

# Options
extra:
  version: 0.3.0
  logo: 'img/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'madrus'
    twitter: 'madrusnl'

# Google Analytics
google_analytics:
  - 'UA-52692182-5'
  - 'auto'

# Extensions
markdown_extensions:
  - fenced_code
  - fontawesome_markdown
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.nl2br
  - markdown.extensions.smarty:
      smart_angled_quotes: true
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Pages structure
nav:
  - Home: index.md
  - MkDocs Engine:
    - Getting started: engine/start.md
    - Markdown Cheatsheet: engine/cheatsheet.md
    - Custom Styling: engine/styling.md
    - Color Styling: engine/colors.md
    - PowerShell Deployments: engine/deployments.md
    - Installation: engine/install.md
    - Technicalities: engine/technicalities.md
  - Aurelia:
    - Some Technical Notes: aurelia/technicalities.md
  - Git:
    - GitFlow: git/gitflow.md
    - Git Prompt Styling: git/styling.md
    - Set up SSH: git/ssh.md
    - Git Command Line Tools: git/tools.md
    - GitDiff: git/gitdiff.md
  - Go:
    - Installing Go: go/myinstall.md
    - Go Notes: go/notes.md
  - Handy Stuff:
    - Chocolatey: handy/choco.md
  - Mac:
    - Homebrew: mac/brew.md
    - NGINX: mac/nginx.md
    - SSH on Sierra: mac/ssh.md
    - Tips & Tricks: mac/tips.md
  - .NET Core:
    - New Project: dotnet/new_project.md
    - Notes: dotnet/notes.md
    - Tips: dotnet/tips.md
  - PowerShell:
    - Debugging PowerShell in VS Code: powershell/vscode.md
  - Umbraco:
    - FAQ: umbraco/faq.md
    - Technicalities: umbraco/technicalities.md
  - Vue.js:
    - Vue.js Basics: vuejs/basics.md
  - Webpack:
    - Webpack Basics: webpack/basics.md
  - Playground:
    - TODOs: playground/todo.md
    - Test Document: playground/test.md
