# Project information
site_name: "Madrus's Docs"
site_description: 'A short description of my project'
site_author: 'Madrus'
site_url: 'http://madrus4u.com/mdocs/'
site_favicon: 'img/favicon.ico'

# Repository
#repo_name: 'GitHub'  # will it work with GitLab?
repo_url: 'https://github.com/madrus/mdocs'

# Pages structure
pages:
  - Home: index.md
  - MkDocs Engine:
    - Technicalities: engine/technicalities.md
    - Styling: engine/styling.md
  - Aurelia:
    - Technicalities: aurelia/technicalities.md
  - .NET Core:
    - New Project: dotnet/new_project.md
    - Notes: dotnet/notes.md
    - Tips: dotnet/tips.md
  - Git:
    - Tools: git/tools.md
    - Styling: git/styling.md
    - SSH: git/ssh.md
  - Umbraco:
    - Technicalities: umbraco/technicalities.md
    - FAQ: umbraco/faq.md
  - Vue.js:
    - Basics: vuejs/basics.md
  - Playground:
    - TODOs: playground/todo.md
    - Test Document: playground/test.md

# Documentation and theme
docs_dir: docs
theme: 'material'

# Options
extra:
  version: 0.2.0
  logo: 'img/logo.png'
  palette:
    primary: 'teal'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'madrus'
    twitter: 'madrusnl'

markdown_extensions:
  - admonition
  - codehilite(css_class=code):
      guess_lang: false
  - fontawesome_markdown
  - nl2br
  - smarty:
      smart_angled_quotes: true

#Copyright
copyright: 'Copyright &copy; 2017 <a href="https://madrus4u.com">Balans4U</a>'

# Google Analytics
google_analytics:
  - 'UA-52692182-5'
  - 'auto'
